### ISSUE TITLE
Fill in about pages text sections

### ISSUE THREAD

**Issue by frostebite** [uksf/Website-Issues#12]

**Comment by AnAngrySalad1** [comment]
Training:

UKSF spends alot of its time operating in smaller teams conducting missions that are usually above their weight. In order to successfully complete these missions every member of a team needs to be on top of their game when carrying out their role. This high standard is a necessity and drives our approach to training.

Everything at UKSF is course based and requires a degree of self motivation to undertake.

Specialist roles include RTO, FAC/JTAC, Medic, Sniper, NCO and Officer whilst none specialist roles include Gunner, Marksman, AT, Recce School and FSG. 

There also other courses that help develop players capabilities such as HALO/HAHO and Radio Training etc.

With varying course lengths and a wide variety, players can expect plenty of options for variation in their game play.

**Comment by AnAngrySalad1** [comment]
Special Forces:

Pathfinders : - 

The units primary reconnaissance, sabotage and strike force. A small elite unit compromising of some of the highest trained members the unit has. Trained to carry out both stealth and overt operations. Pathfinders operate in isolation behind enemy lines conducting a variety of mission types in support of the wider operation.

SAS:

Content content content (TBC)
